# Generated by Django 5.0.4 on 2024-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0002_tableresto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableresto",
            name="code",
            field=models.CharField(default="3456", max_length=20),
        ),
        migrations.AlterField(
            model_name="tableresto",
            name="name",
            field=models.CharField(default="Meja 1", max_length=100),
        ),
    ]
