# Generated by Django 5.0.6 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0002_alter_tableresto_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableresto",
            name="status",
            field=models.CharField(
                choices=[("Aktif", "Aktif"), ("Tidak Aktif", "Tidak Aktif")],
                default="Aktif",
                max_length=15,
            ),
        ),
    ]
