# Generated by Django 5.0.6 on 2024-05-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0003_alter_tableresto_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableresto",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_table_resto",
                to="pos_app.statusmodel",
            ),
        ),
    ]
