# Generated by Django 5.0.4 on 2024-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0003_alter_tableresto_code_alter_tableresto_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableresto",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tableresto",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
